### ISSUE TITLE
Página inicial - Tabs

### ISSUE THREAD

**Issue by CGallardo98** [CGallardo98/CodeNet#6]
Completar el componente Tabs.jsx:

- [x] Comparar archivos para incluir lo necesario y que no haya conflictos.

- [x] Cambiar el código de App.jsx de la carpeta generada y ponerlo dentro de la función correspondiente en HomePage.jsx

- [x] Revisar el archivo index.html de la carpeta generada y ver cómo incluirlo en el index.html del proyecto

**Comment by ju4n1t4** [comment]
Instalar Carrousel:

npm install react-slick slick-carousel
